name: My first workflow

on: 
    push
 
jobs:
    my-job1:
        runs-on: ubuntu-latest
        steps:
        - name: diplay env
          run: |
            echo ${{ secrets.DOCKER_PASSWORD }}
            echo ${{ vars.DOCKER_USERNAME}}
          